---
title: 'BehAV: Labeling Tools'
author: "Daniel N. Albohn"
date: "`r Sys.time()`"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    number_sections: true
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, error = FALSE, message = FALSE,
                      eval = FALSE)
library(tidyverse)
library(knitr)
library(kableExtra)
```

# Resources

- [Awesome data labeling](https://github.com/heartexlabs/awesome-data-labeling)
- GitHub Topics
  - [annotation-tool](https://github.com/topics/annotation-tool)
  - [video-annotation](https://github.com/topics/video-annotation)
  
# Potential Labelers

The labeler **needs** to have the following attributes:

- Ability to handle both images and video
- Import/export annotations
- Some sort of layered annotations for comparisons

The labeler will **preferably** have the following:

- Import/export multiple types of annotations (e.g., `.csv`,`.json`)
- Add meta-data
- Toggle number of videos present

## [Microsoft Visual Object Tagging Tool](https://github.com/microsoft/VoTT)
Visual Object Tagging Tool: An electron app for building end to end Object
Detection Models from Images and Videos.

- Can run locally or in a web app
  - Web app cannot access local file system
  - webapp [Docker image](https://hub.docker.com/r/jcjimenez/vott-web/)
- No way to import external data

## [Labelbox](https://github.com/Labelbox/Labelbox)
Labelbox is the fastest way to annotate data to build and ship computer vision applications.

- Written in javascript
- Easily create custom interfaces
- Video analysis seems to be proprietary (https://www.labelbox.com/pricing)

## [UltimateLabeling](https://github.com/alexandre01/UltimateLabeling)
A multi-purpose Video Labeling GUI in Python with integrated SOTA detector and tracker.

- Ability to import pre-existing files:

> Import labels: To import existing .CSV labels, hit Cmd+I (or Ctrl+I).
  UltimateLabeling expects to read one .CSV file per frame, 
  in the format: "class_id", "xc", "yc", "w", "h".

- `csv` file import/export
- Can connect to remote server via `ssh`
- YOLO integration
- Seems to be under active development (i.e., missing some features)

## [cvat](https://github.com/opencv/cvat)
Powerful and efficient Computer Vision Annotation Tool (CVAT)

- `XML` file output
- Can only be run in Google Chrome
- Run via docker compose (i.e., multiple containers), which is incompatible with
singularity (as far as I know)

## [ViPER](http://viper-toolkit.sourceforge.net/)

- Written in Java (cross platform)
- Loads annotations via `XML`
- Relatively old (2015)

## [Anvil](https://www.anvil-software.org/)

- Written in Java
- Relatively old (2015)
  
## [sloth](https://github.com/cvhciKIT/sloth)
Sloth is a tool for labeling image and video data for computer vision research.

[Installation guide](https://sloth.readthedocs.io/en/latest/installation.html)

## [labelme](https://github.com/wkentaro/labelme)
Image Polygonal Annotation with Python (polygon, rectangle, circle, line, point and
image-level flag annotation).

- Written in python
- Pre-made [Docker image](https://github.com/wkentaro/labelme#docker)

## [SimpleVideoAnnotation](https://github.com/CarlosPena00/SimpleVideoAnnotation)
A simple video annotation made with python + OpenCV for detection in YoloV2 format

## [video_annotation](https://github.com/danoneata/video_annotation)
Annotation tool for videos

- Written in python
- Run as a server

## [label-v](https://github.com/innovationgarage/label-V)
semi-automatic video annotation tool

- Written in python
- Runs in browswer
- Outputs `json`

## [scaleabel](https://github.com/ucbdrive/scalabel)
Quantify computer vision performance in human terms

- Run in browser
- Can upload image lists and annotations as `json`
  - [Example file](https://github.com/ucbdrive/scalabel/blob/master/examples/image_list_with_auto_labels.json)

## [vactic.js](https://github.com/dbolkensteyn/vatic.js)
vatic.js A pure Javascript video annotation tool

- Run in browser
- Outputs `XML`

# Best leads
Based on the initial skimming of annotation software, the following appear to be
the most viable for the current project. None are perfectly suitable for
the project purpose, but may be useful nonetheless.

1. [UltimateLabeling](https://github.com/alexandre01/UltimateLabeling)

2. [scalable](https://github.com/ucbdrive/scalabel)

3. [labelme](https://github.com/wkentaro/labelme)

4. [video_annotation](https://github.com/danoneata/video_annotation)

5. [vactic.js](https://github.com/dbolkensteyn/vatic.js)

6. [label-v](https://github.com/innovationgarage/label-V)

7. [cvat](https://github.com/opencv/cvat)
    + Stretch goal. Very pretty and feature-rich, but I don't think I can
    get it working on ACI since it relies on docker-compose.

# Use case notes and results


